language: rust
dist: trusty
sudo: required
cache: cargo
addons:
  apt:
    packages:
    - libssl-dev
env:
    global:
        - CRATE_NAME=cargo-tarpaulin
rust:
- stable 
- beta
- nightly
script:
- cargo clean
- RUST_BACKTRACE=1 cargo build
- cargo test -- --test-threads 1
- |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      cargo test -- --test-threads 1 --ignored
  fi
after_success: |
    test $TRAVIS_BRANCH = develop &&
    test $TRAVIS_RUST_VERSION = nightly &&
    ./ci/trigger_docker_build.sh
before_deploy:
    - cargo package
    # This avoids trying to publish with a dirty repo
    - cargo publish --token "$CRATES_IO_TOKEN"
    - sh ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: alh4vvlwOLaKGJhW/j2d5W+EEGGoFmPYq+ECmwQCLtzLLQWjKyo53aYxSdMD6nXNYK3gkLeQX27ZmestYv6Jg4VrIBjkuMJ3UPxylzxhJDi+3hHmkKyprS/YfZNbm+RGK8J5YHwIf30kyjsbYmtg0zcQvmZI6MDLpq4bPHgkjTNVPTe9bHTbvPEs0Jo4jBs+IwebsNGXGEbHcRypE5HT9k/LaaULdrtvocK+r5gMXZOHzBZusvBV8V3Epyl7+abi/JsMvF+3KRw/fy+Wj2f+laZKvSfOkiKmkuoGF8udouxvBeAE7L5V0gqtP8ZbwbpQmmsIKDtNZwOeXO13x/EwSOtGYIwfiL6Wv7Z2UZ1uJaVgVA3h7QiPVum4j8hBcZf9gNqCAU5htWpC2dLvlN/pNqkczvL8qxBAXjl9Y+RJB1hmWirCDAPuTCqbSVp9R1QDmoA8z4RGFCskTjRBY6pvda9Oum1ZRk3ouD8Kxvsb8P4j9xTHgfNsO+x2J6UaCBldI8tWRVS49Qm2i0S4hsRQYLRVxvd2T+5GwLfAJkMj2xO+UkVzvWHQL/rQOlgHh69al3Pl++Zh5W4grSjJYV1EwvRkitDegmwUATev8LkRtEQD+QBSKpTsatcZgfxZqNioPVZhogl0R+l9tOSgiujSVHNEZxLhjMTos54sRJLvdw4=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-travis.*
  skip_cleanup: true
  on:
    repo: xd009642/tarpaulin
    condition: $TRAVIS_RUST_VERSION = nightly
    tags: true
